# Generated by Django 4.0.4 on 2022-09-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('summery', models.TextField()),
                ('degree', models.CharField(max_length=300)),
                ('school', models.CharField(max_length=300)),
                ('university', models.CharField(max_length=300)),
                ('previous_work', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
